# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_carga_inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_carga(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 312)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setEnabled(True)
        self.main_frame.setGeometry(QtCore.QRect(10, 110, 431, 131))
        self.main_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.301, x2:1, y2:0.75, stop:0 rgba(247, 186, 121, 255), stop:1 rgba(227, 68, 64, 255));\n"
"border-radius: 20px;\n"
"border-bottom: 5px solid rgb(12, 48, 57);\n"
"border-right:  5px solid rgb(12, 48, 57);\n"
"border-top:  5px solid rgb(12, 48, 57);\n"
"border-left:  5px solid rgb(12, 48, 57);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.borde_frame = QtWidgets.QFrame(self.main_frame)
        self.borde_frame.setGeometry(QtCore.QRect(0, 30, 561, 331))
        self.borde_frame.setStyleSheet("background-color: none;\n"
"border: 10px solid rgb(12, 48, 57);\n"
"border-radius: 60px;")
        self.borde_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.borde_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.borde_frame.setObjectName("borde_frame")
        self.titulo_label = QtWidgets.QLabel(self.borde_frame)
        self.titulo_label.setGeometry(QtCore.QRect(20, 10, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titulo_label.setFont(font)
        self.titulo_label.setAcceptDrops(False)
        self.titulo_label.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: rgb(25, 25, 25);")
        self.titulo_label.setTextFormat(QtCore.Qt.AutoText)
        self.titulo_label.setScaledContents(False)
        self.titulo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_label.setWordWrap(True)
        self.titulo_label.setObjectName("titulo_label")
        self.infromacion_frame = QtWidgets.QFrame(self.centralwidget)
        self.infromacion_frame.setGeometry(QtCore.QRect(10, 220, 431, 81))
        self.infromacion_frame.setStyleSheet("background-color: rgb(17, 66, 79);\n"
"border-radius: 20px;\n"
"border: 5px solid rgb(9, 36, 43);")
        self.infromacion_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infromacion_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infromacion_frame.setObjectName("infromacion_frame")
        self.desarrollador_label = QtWidgets.QLabel(self.infromacion_frame)
        self.desarrollador_label.setGeometry(QtCore.QRect(20, 50, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.desarrollador_label.setFont(font)
        self.desarrollador_label.setStyleSheet("border:none;\n"
"background-color:none;\n"
"color: rgb(255, 255, 255);")
        self.desarrollador_label.setObjectName("desarrollador_label")
        self.iniciando_app = QtWidgets.QLabel(self.infromacion_frame)
        self.iniciando_app.setGeometry(QtCore.QRect(20, 20, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.iniciando_app.setFont(font)
        self.iniciando_app.setStyleSheet("border:none;\n"
"background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.iniciando_app.setObjectName("iniciando_app")
        self.fondo_imagen_frame = QtWidgets.QFrame(self.centralwidget)
        self.fondo_imagen_frame.setGeometry(QtCore.QRect(40, 10, 371, 121))
        self.fondo_imagen_frame.setStyleSheet("border-radius: 20px;\n"
"/*border: 5px solid rgb(17, 66, 79);*/\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.494318, y2:0.034, stop:0 rgba(228, 75, 68, 255), stop:1 rgba(247, 186, 121, 57));")
        self.fondo_imagen_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_imagen_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_imagen_frame.setObjectName("fondo_imagen_frame")
        self.frame_image = QtWidgets.QFrame(self.centralwidget)
        self.frame_image.setGeometry(QtCore.QRect(40, 11, 371, 131))
        self.frame_image.setStyleSheet("image: url(:/imagenes/imagenes/manos.png);\n"
"background:none;")
        self.frame_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_image.setObjectName("frame_image")
        self.fondo_imagen_frame.raise_()
        self.main_frame.raise_()
        self.infromacion_frame.raise_()
        self.frame_image.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo_label.setText(_translate("MainWindow", "Traducción de la Lengua de Señas Boliviana"))
        self.desarrollador_label.setText(_translate("MainWindow", "Desarrollado por Freddy Villca Villegas"))
        self.iniciando_app.setText(_translate("MainWindow", "Iniciando aplicación ..."))
import interfaz_carga_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
