# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1270, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(10, 10, 1200, 710))
        self.main_frame.setTabletTracking(True)
        self.main_frame.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"/*border: 2px solid rgb(184, 184, 184);*/\n"
"\n"
"")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.salir_Button = QtWidgets.QPushButton(self.main_frame)
        self.salir_Button.setGeometry(QtCore.QRect(1110, 20, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.salir_Button.setFont(font)
        self.salir_Button.setStyleSheet("QPushButton {    \n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(244, 64, 94);\n"
"}\n"
"\n"
"")
        self.salir_Button.setObjectName("salir_Button")
        self.image_label = QtWidgets.QLabel(self.main_frame)
        self.image_label.setGeometry(QtCore.QRect(20, 90, 640, 480))
        self.image_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;\n"
"border: 2px solid rgb(200, 200, 200);")
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.texto_trad_label = QtWidgets.QLabel(self.main_frame)
        self.texto_trad_label.setGeometry(QtCore.QRect(20, 580, 641, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.texto_trad_label.setFont(font)
        self.texto_trad_label.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"border: 3px solid rgb(184, 184, 184);")
        self.texto_trad_label.setText("")
        self.texto_trad_label.setScaledContents(False)
        self.texto_trad_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.texto_trad_label.setWordWrap(True)
        self.texto_trad_label.setIndent(-1)
        self.texto_trad_label.setObjectName("texto_trad_label")
        self.titulo_label = QtWidgets.QLabel(self.main_frame)
        self.titulo_label.setGeometry(QtCore.QRect(20, 8, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_label.setFont(font)
        self.titulo_label.setStyleSheet("color: rgb(0, 0, 0);\n"
"border:none;")
        self.titulo_label.setObjectName("titulo_label")
        self.cam_comboBox = QtWidgets.QComboBox(self.main_frame)
        self.cam_comboBox.setGeometry(QtCore.QRect(30, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cam_comboBox.setFont(font)
        self.cam_comboBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"border:none;")
        self.cam_comboBox.setEditable(False)
        self.cam_comboBox.setObjectName("cam_comboBox")
        self.cam_comboBox.addItem("")
        self.cam_comboBox.addItem("")
        self.conten_frame = QtWidgets.QFrame(self.main_frame)
        self.conten_frame.setGeometry(QtCore.QRect(680, 0, 521, 710))
        self.conten_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(241, 154, 81, 255), stop:1 rgba(245, 51, 96, 255));\n"
"border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;")
        self.conten_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.conten_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conten_frame.setObjectName("conten_frame")
        self.alfab_frame = QtWidgets.QFrame(self.conten_frame)
        self.alfab_frame.setGeometry(QtCore.QRect(80, 90, 371, 471))
        self.alfab_frame.setStyleSheet("image: url(:/imagenes/imagenes/abecedario.png);\n"
"border: none;\n"
"background-color: none;\n"
"")
        self.alfab_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.alfab_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alfab_frame.setObjectName("alfab_frame")
        self.guardar_Button = QtWidgets.QPushButton(self.conten_frame)
        self.guardar_Button.setGeometry(QtCore.QRect(370, 600, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.guardar_Button.setFont(font)
        self.guardar_Button.setStyleSheet("QPushButton {    \n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(98, 159, 217);\n"
"}\n"
"")
        self.guardar_Button.setObjectName("guardar_Button")
        self.borrar_Button = QtWidgets.QPushButton(self.conten_frame)
        self.borrar_Button.setGeometry(QtCore.QRect(250, 600, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.borrar_Button.setFont(font)
        self.borrar_Button.setStyleSheet("QPushButton {    \n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(170, 85, 255);\n"
"}")
        self.borrar_Button.setObjectName("borrar_Button")
        self.inicio_Button = QtWidgets.QPushButton(self.conten_frame)
        self.inicio_Button.setGeometry(QtCore.QRect(50, 600, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inicio_Button.setFont(font)
        self.inicio_Button.setStyleSheet("QPushButton {    \n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(170, 255, 127);\n"
"}")
        self.inicio_Button.setObjectName("inicio_Button")
        self.detener_Button = QtWidgets.QPushButton(self.conten_frame)
        self.detener_Button.setGeometry(QtCore.QRect(150, 600, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.detener_Button.setFont(font)
        self.detener_Button.setStyleSheet("QPushButton {    \n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(97, 195, 144);\n"
"}\n"
"")
        self.detener_Button.setObjectName("detener_Button")
        self.subtitulo_label = QtWidgets.QLabel(self.conten_frame)
        self.subtitulo_label.setGeometry(QtCore.QRect(140, 50, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subtitulo_label.setFont(font)
        self.subtitulo_label.setStyleSheet("color: rgb(0, 0, 0);\n"
"border:none;\n"
"background-color:none;")
        self.subtitulo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitulo_label.setObjectName("subtitulo_label")
        self.borrarultima_Button = QtWidgets.QPushButton(self.conten_frame)
        self.borrarultima_Button.setGeometry(QtCore.QRect(50, 653, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.borrarultima_Button.setFont(font)
        self.borrarultima_Button.setStyleSheet("QPushButton {    \n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(243, 91, 90);\n"
"}")
        self.borrarultima_Button.setObjectName("borrarultima_Button")
        self.umbral_slider = QtWidgets.QSlider(self.main_frame)
        self.umbral_slider.setGeometry(QtCore.QRect(290, 55, 160, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.umbral_slider.setFont(font)
        self.umbral_slider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: rgb(241, 147, 82);\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    width: 14px;\n"
"    margin: -2px 0;\n"
"    border-radius: 5px;\n"
"}")
        self.umbral_slider.setMinimum(0)
        self.umbral_slider.setMaximum(100)
        self.umbral_slider.setSingleStep(10)
        self.umbral_slider.setSliderPosition(50)
        self.umbral_slider.setOrientation(QtCore.Qt.Horizontal)
        self.umbral_slider.setInvertedAppearance(False)
        self.umbral_slider.setInvertedControls(False)
        self.umbral_slider.setObjectName("umbral_slider")
        self.umbral_label = QtWidgets.QLabel(self.main_frame)
        self.umbral_label.setGeometry(QtCore.QRect(457, 47, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.umbral_label.setFont(font)
        self.umbral_label.setAlignment(QtCore.Qt.AlignCenter)
        self.umbral_label.setObjectName("umbral_label")
        self.text_umbral = QtWidgets.QLabel(self.main_frame)
        self.text_umbral.setGeometry(QtCore.QRect(150, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_umbral.setFont(font)
        self.text_umbral.setAlignment(QtCore.Qt.AlignCenter)
        self.text_umbral.setObjectName("text_umbral")
        self.proba_label = QtWidgets.QLabel(self.main_frame)
        self.proba_label.setGeometry(QtCore.QRect(40, 670, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.proba_label.setFont(font)
        self.proba_label.setObjectName("proba_label")
        self.encabezado_frame = QtWidgets.QFrame(self.main_frame)
        self.encabezado_frame.setGeometry(QtCore.QRect(500, 0, 601, 41))
        self.encabezado_frame.setStyleSheet("border-radius: 0px;\n"
"background-color: none;")
        self.encabezado_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.encabezado_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.encabezado_frame.setObjectName("encabezado_frame")
        self.conten_frame.raise_()
        self.salir_Button.raise_()
        self.image_label.raise_()
        self.texto_trad_label.raise_()
        self.titulo_label.raise_()
        self.cam_comboBox.raise_()
        self.umbral_slider.raise_()
        self.umbral_label.raise_()
        self.text_umbral.raise_()
        self.proba_label.raise_()
        self.encabezado_frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.salir_Button.setText(_translate("MainWindow", "salir"))
        self.titulo_label.setText(_translate("MainWindow", "Traducción del deletreo manual de la LSB a texto"))
        self.cam_comboBox.setItemText(0, _translate("MainWindow", "Cámara 0"))
        self.cam_comboBox.setItemText(1, _translate("MainWindow", "Cámara 1"))
        self.guardar_Button.setText(_translate("MainWindow", "Guardar Texto"))
        self.borrar_Button.setText(_translate("MainWindow", "Borrar Todo"))
        self.inicio_Button.setText(_translate("MainWindow", "Iniciar"))
        self.detener_Button.setText(_translate("MainWindow", "Detener"))
        self.subtitulo_label.setText(_translate("MainWindow", "Alfabeto Dactilológico Boliviano"))
        self.borrarultima_Button.setText(_translate("MainWindow", "Borrar ultima predicción"))
        self.umbral_label.setText(_translate("MainWindow", "0.50"))
        self.text_umbral.setText(_translate("MainWindow", "Umbral detección"))
        self.proba_label.setText(_translate("MainWindow", "Probabilidad ultima: "))
import ventana_principal_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
